// <autogenerated>
//   This file was generated by T4 code generator ContractsCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using OSharp.Core;
using OSharp.Utility.Data;
using System.Linq.Expressions;
using System.Threading.Tasks;
using OSharp.Core.Dependency;
using Bode.Services.Core.Dtos.Character;
using Bode.Services.Core.Models.Character;

namespace Bode.Services.Core.Contracts
{
    public partial interface ICharacterContract : IScopeDependency
    {
        /// <summary>
        /// 保存用户设置标签
        /// </summary>
        /// <param name="userId">用户ID</param>
        /// <param name="ids">用户设置的标签ID</param>
        /// <returns></returns>
        OperationResult SaveLabels(int userId, int[] ids);
    }
}
